# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build CLI for Linux
      run: GOOS=linux GOARCH=amd64 go build -o beta ./cmd

    - name: Build CLI for Windows
      run: GOOS=windows GOARCH=amd64 go build -o beta.exe ./cmd

    - name: Build Docker CLI image
      run: |
        echo 'FROM scratch' > Dockerfile
        echo 'COPY beta /app' >> Dockerfile
        docker build -t beta:latest .

    - name: Upload Linux binary
      uses: actions/upload-artifact@v3
      with:
        name: beta-linux
        path: beta

    - name: Upload Windows binary
      uses: actions/upload-artifact@v3
      with:
        name: beta-windows
        path: beta.exe
    
    - name: Upload Dockerfile
      uses: actions/upload-artifact@v3
      with:
        name: dockerfile
        path: Dockerfile
